apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orderflow
  namespace: default
spec:
  rules:
    - host: orderflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orderflow-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: orderflow-api-gateway
                port:
                  number: 80
