{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: orderflow-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  EXAMPLE_API_KEY: {{ .Values.secrets.exampleApiKey | quote }}
{{- end }}
