services:
  customer:
    build:
      context: ./services/customer
    ports:
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8001/healthz').read()" ]
      interval: 10s
      timeout: 3s
      retries: 5

  order:
    build:
      context: ./services/order
    ports:
      - "8002:8002"
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8002/healthz').read()" ]
      interval: 10s
      timeout: 3s
      retries: 5
