apiVersion: v2
name: orderflow
description: A Helm chart for the OrderFlow microservices application
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  - name: auth
    version: 0.1.0
    repository: file://./charts/auth
  - name: customer
    version: 0.1.0
    repository: file://./charts/customer
  - name: catalog
    version: 0.1.0
    repository: file://./charts/catalog
  - name: order
    version: 0.1.0
    repository: file://./charts/order
  - name: production
    version: 0.1.0
    repository: file://./charts/production
  - name: api-gateway
    version: 0.1.0
    repository: file://./charts/api-gateway
  - name: frontend
    version: 0.1.0
    repository: file://./charts/frontend
