namespace: orderflow

images:
  repo:
    customer: ghcr.io/haimazulay/orderflow-customer
    order: ghcr.io/haimazulay/orderflow-order
    gateway: ghcr.io/haimazulay/orderflow-gateway
    frontend: ghcr.io/haimazulay/orderflow-frontend
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

service:
  gateway:
    type: LoadBalancer
    port: 8000
  frontend:
    type: ClusterIP
    port: 80

secrets:
  enabled: true
  apiKey: ""

persistence:
  enabled: true
  storageClassName: ""  
  size: 1Gi
  customerMountPath: /app/data
  orderMountPath: /app/data

gateway:
  customerUrl: "http://customer:8001"
  orderUrl: "http://order:8002"

