name: CD Deploy (Docker Desktop)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push images (version tag)
        shell: bash
        run: |
          OWNER_LC="$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          TAG="${{ github.ref_name }}"

          docker buildx build --push -t ghcr.io/$OWNER_LC/orderflow-customer:$TAG ./services/customer
          docker buildx build --push -t ghcr.io/$OWNER_LC/orderflow-order:$TAG ./services/order
          docker buildx build --push -t ghcr.io/$OWNER_LC/orderflow-gateway:$TAG ./services/api-gateway
          docker buildx build --push -t ghcr.io/$OWNER_LC/orderflow-frontend:$TAG ./frontend

  deploy-helm:
    runs-on: self-hosted
    environment: local
    needs: [ build-and-push ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

        if: github.repository_owner == 'haimazulay'

      - name: Setup kubeconfig
        shell: bash
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_DATA}" > $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy via Helm (tag -> image)
        shell: bash
        run: |
          TAG="${{ github.ref_name }}"
          helm upgrade --install orderflow ./helm/orderflow -n orderflow --create-namespace \
            --set images.customer=ghcr.io/${{ github.repository_owner }}/orderflow-customer:${TAG} \
            --set images.order=ghcr.io/${{ github.repository_owner }}/orderflow-order:${TAG} \
            --set images.gateway=ghcr.io/${{ github.repository_owner }}/orderflow-gateway:${TAG} \
            --set images.frontend=ghcr.io/${{ github.repository_owner }}/orderflow-frontend:${TAG}
