name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ "customer", "order", "api-gateway" ]
    defaults:
      run:
        working-directory: services/${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [ test-python, test-frontend ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # CUSTOMER
      - name: Meta (customer)
        id: meta_customer
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/orderflow-customer
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build & Push (customer)
        uses: docker/build-push-action@v6
        with:
          context: ./services/customer
          push: true
          tags: ${{ steps.meta_customer.outputs.tags }}
          labels: ${{ steps.meta_customer.outputs.labels }}

      # ORDER
      - name: Meta (order)
        id: meta_order
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/orderflow-order
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build & Push (order)
        uses: docker/build-push-action@v6
        with:
          context: ./services/order
          push: true
          tags: ${{ steps.meta_order.outputs.tags }}
          labels: ${{ steps.meta_order.outputs.labels }}

      # GATEWAY
      - name: Meta (gateway)
        id: meta_gateway
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/orderflow-gateway
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build & Push (gateway)
        uses: docker/build-push-action@v6
        with:
          context: ./services/api-gateway
          push: true
          tags: ${{ steps.meta_gateway.outputs.tags }}
          labels: ${{ steps.meta_gateway.outputs.labels }}

      # FRONTEND
      - name: Meta (frontend)
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/orderflow-frontend
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build & Push (frontend)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
